-- ============================================================
-- SENA Bienestar - Esquema completo de base de datos
-- Ejecutar en Supabase SQL Editor
-- ============================================================

-- 1. TABLA DE ROLES
CREATE TABLE if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  permissions jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

-- 2. TABLA DE DEPENDENCIAS (Psicología, Enfermería, Trabajo Social)
CREATE TABLE if not exists public.dependencies (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text default '#39a900',
  created_at timestamptz default now()
);

-- 3. TABLA DE PERFILES (extiende auth.users)
CREATE TABLE if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  document_number text unique,
  email text,
  role_id bigint references public.roles(id),
  dependency_id bigint references public.dependencies(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4. TABLA DE CITAS
CREATE TABLE if not exists public.appointments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  professional_id uuid references public.profiles(id),
  dependency_id bigint references public.dependencies(id),
  scheduled_date date not null,
  scheduled_time time not null,
  status text not null default 'pending' check (status in ('pending','confirmed','completed','cancelled','no_show')),
  reason text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ============================================================
-- DATOS INICIALES
-- ============================================================

-- Insertar roles
INSERT INTO public.roles (name, permissions) VALUES
  ('APRENDIZ', '{"can_book": true, "max_pending": 2}'),
  ('PSICOLOGIA', '{"can_manage_appointments": true}'),
  ('ENFERMERIA', '{"can_manage_appointments": true}'),
  ('TRABAJO_SOCIAL', '{"can_manage_appointments": true}'),
  ('COORDINACION', '{"can_view_all": true, "can_export": true}'),
  ('SUPERADMIN', '{"can_manage_all": true}')
ON CONFLICT (name) DO NOTHING;

-- Insertar dependencias
INSERT INTO public.dependencies (name, color) VALUES
  ('Psicología', '#3b82f6'),
  ('Enfermería', '#22c55e'),
  ('Trabajo Social', '#f59e0b')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- TRIGGER: Crear perfil automáticamente al registrarse
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, document_number, email, role_id)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data ->> 'full_name', ''),
    COALESCE(new.raw_user_meta_data ->> 'document_number', ''),
    new.email,
    COALESCE(new.raw_user_meta_data ->> 'role_id', 'APRENDIZ')
  );
  RETURN new;
END;
$$;

-- Vincular el trigger a auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- CONFIRMAR EMAILS EXISTENTES
-- ============================================================
UPDATE auth.users SET email_confirmed_at = now()
WHERE email_confirmed_at IS NULL;

-- ============================================================
-- FUNCIÓN PARA AUTO-CONFIRMAR EMAILS
-- ============================================================

CREATE OR REPLACE FUNCTION public.confirm_email(target_email text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  UPDATE auth.users 
  SET email_confirmed_at = now() 
  WHERE email = target_email 
  AND email_confirmed_at IS NULL;
  RETURN FOUND;
END;
$$;

GRANT EXECUTE ON FUNCTION public.confirm_email TO anon;
GRANT EXECUTE ON FUNCTION public.confirm_email TO authenticated;

-- ============================================================
-- FUNCIÓN PARA KPI DEL DASHBOARD
-- ============================================================

DROP FUNCTION IF EXISTS public.get_dashboard_kpis(date, date);

CREATE OR REPLACE FUNCTION public.get_dashboard_kpis(start_date date, end_date date)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result jsonb;
BEGIN
  SELECT jsonb_build_object(
    'total_appointments', count(*),
    'pending_appointments', count(*) filter (where status = 'pending'),
    'completed_appointments', count(*) filter (where status = 'completed'),
    'total_users', (select count(*) from public.profiles)
  ) INTO result
  FROM public.appointments
  WHERE scheduled_date >= start_date AND scheduled_date <= end_date;

  RETURN result;
END;
$$;

-- ============================================================
-- FUNCIÓN PARA TENDENCIA MENSUAL
-- ============================================================

DROP FUNCTION IF EXISTS public.get_monthly_appointments(int);

CREATE OR REPLACE FUNCTION public.get_monthly_appointments(year_param int)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result jsonb;
BEGIN
  SELECT jsonb_agg(jsonb_build_object(
    'month', to_char(month_series, 'YYYY-MM'),
    'total', coalesce(counts.c, 0)
  ) ORDER BY month_series) INTO result
  FROM generate_series(
    make_date(year_param, 1, 1),
    make_date(year_param, 12, 1),
    interval '1 month'
  ) month_series
  LEFT JOIN (
    SELECT date_trunc('month', scheduled_date)::date as m, count(*) as c
    FROM public.appointments
    WHERE date_trunc('month', scheduled_date)::date BETWEEN make_date(year_param, 1, 1) AND make_date(year_param, 12, 1)
    GROUP BY m
  ) counts ON month_series = counts.m;

  RETURN coalesce(result, '[]'::jsonb);
END;
$$;

-- ============================================================
-- RLS (Row Level Security) básico
-- ============================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dependencies ENABLE ROW LEVEL SECURITY;

-- Políticas: perfiles
CREATE POLICY "profiles_select_own" ON public.profiles
  FOR SELECT USING (auth.uid() = id OR EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role_id IN (
      SELECT id FROM public.roles WHERE name IN ('COORDINACION', 'SUPERADMIN')
    )
  ));

CREATE POLICY "profiles_update_own" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Políticas: citas
CREATE POLICY "appointments_select" ON public.appointments
  FOR SELECT USING (
    user_id = auth.uid() OR
    professional_id = auth.uid() OR
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role_id IN (
      SELECT id FROM public.roles WHERE name IN ('COORDINACION', 'SUPERADMIN')
    ))
  );

CREATE POLICY "appointments_insert" ON public.appointments
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "appointments_update" ON public.appointments
  FOR UPDATE USING (
    user_id = auth.uid() OR
    professional_id = auth.uid() OR
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role_id IN (
      SELECT id FROM public.roles WHERE name IN ('COORDINACION', 'SUPERADMIN')
    ))
  );
